### ISSUE TITLE
`useChainSpecData` Hook: 'Method not found' Error in Local People Rococo Instance

### ISSUE THREAD

**Issue by 71walceli** [tien/reactive-dot#297]
I'm encountering an "Uncaught RpcError: Method not found" error when attempting to use the useChainSpecData hook to retrieve chain-specific data (like decimal places and coin symbol) from a local People Rococo instance.

```ts
const chainData = useChainSpecData({ chainId: "people_rococo" });
```

But it always throws the error:

```
Uncaught RpcError: Method not found
    at onMessage (chunk-UWJJAIAH.js?v=42992e8a:1126:35)
    at onMsgFromProvider (chunk-JOIVRIHN.js?v=42992e8a:30:27)
    at WebSocket._onMessage (@polkadot-api_ws-provider_web.js?v=42992e8a:95:43)
```

My `package.json`

```json
{
  "name": "w3reg-www",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite --host",
    "build": "tsc && vite build",
    "preview": "vite preview",
    "lint": "eslint .",
    "lint:fix": "eslint . --fix",
    "metadata": "bunx papi update",
    "postinstall": "bunx papi"
  },
  "dependencies": {
    "@iconify/react": "^5.0.2",
    "@polkadot-api/descriptors": "file:.papi/descriptors",
    "@polkadot-api/docgen": "^0.0.8",
    "@polkadot-api/metadata-builders": "^0.8.2",
    "@polkadot-api/substrate-bindings": "^0.9.2",
    "@polkadot-api/utils": "^0.1.2",
    "@polkadot/api": "^14.0.1",
    "@reactive-dot/core": "^0.16.5",
    "@reactive-dot/react": "^0.16.5",
    "@reactive-dot/utils": "^0.8.1",
    "@reactive-dot/wallet-ledger": "^0.16.5",
    "@reactive-dot/wallet-walletconnect": "^0.16.5",
    "@unocss/reset": "^0.63.4",
    "bun": "^1.1.30",
    "dot-connect": "^0.11.0",
    "dot-identicon": "^0.1.0",
    "lit-html": "^3.2.1",
    "polkadot-api": "^1.6.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^6.27.0",
    "rxjs": "^7.8.1",
    "unicorn-magic": "0.1.0",
    "valtio": "^2.0.0"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^3.7.3",
    "@types/node": "^22.7.5",
    "@types/react": "^18.3.11",
    "@types/react-dom": "^18.3.1",
    "@unocss/preset-attributify": "^0.63.4",
    "@vitejs/plugin-react-swc": "^3.7.1",
    "eslint": "^9.12.0",
    "typescript": "^5.6.3",
    "unocss": "^0.63.4",
    "vite": "^5.4.8"
  },
  "packageManager": "yarn@4.5.0+sha512.837566d24eec14ec0f5f1411adb544e892b3454255e61fdef8fd05f3429480102806bac7446bc9daff3896b01ae4b62d00096c7e989f1596f2af10b927532f39"
}

```

I'd appreciate your help in solving this, I'm willing to give al other information necessary to help identify

**Comment by 71walceli** [comment]
I was able to get out the decimal count and symbol via following code:

```ts
const chainClient = useClient({ chainId: "people_rococo" })

useEffect(() => {
  const props = chainClient._request("system_properties")
}
```

**Comment by tien** [comment]
@71walceli can you try using the `withPolkadotSdkCompat` and see if this problem still persist?

```ts
import { withPolkadotSdkCompat } from "polkadot-api/polkadot-sdk-compat";

export const config = defineConfig({
  // ...
  people_rococo: {
    // ...
    provider: withPolkadotSdkCompat(getWsProvider("wss://your-rpc.your-url.xyz")),
  }
});
```

If that doesn't help, then it might worth creating an issue over at https://github.com/polkadot-api/polkadot-api/issues, because all that hook does is calling `client.getChainSpecData()`.

**Comment by 71walceli** [comment]
Yes sir, that worked! Thx man!

**Comment by 71walceli** [comment]
Is it possible to use `withPolkadotSdkCompat` with new lightClient API? 

Recently, I had an issue deploying with a workflow, as well as building in Docker. Even dev instance will crash with following error:

```
Uncaught RpcError: Method not found
    at onMessage (chunk-VKKI2RAQ.js?v=e4186cfb:1714:35)
    at @polkadot-api_ws-provider_web.js?v=e4186cfb:58:7
    at onMsgFromProvider (chunk-4CBJKWZL.js?v=e4186cfb:30:27)
    at WebSocket._onMessage (@polkadot-api_ws-provider_web.js?v=e4186cfb:181:45)
```

I tried the following:
- withPolkadotSdkCompat(createLightClientProvider())
- withPolkadotSdkCompat(lightClientProvider.addRelayChain({ id: "kusama" }))
- withPolkadotSdkCompat(polkadotProvider.addParachain({ id: "kusama" }))

But all throw:

```
Uncaught TypeError: base is not a function
    at toParsed (polkadot-api_polkadot-sdk-compat.js?v=a0b9239c:8:32)
    at polkadot-api_polkadot-sdk-compat.js?v=a0b9239c:42:86
    at getProviders (config.ts:21:31)
    at config.ts:32:24
```

It does work well on my current dev environment, but will break apart on any other environment. I could have some dep issues for all I know. Please let me know if I'm missing something. Thanks in advance.

**Comment by tien** [comment]
Light client doesn't need to `compat` enhancer, if you check the error message, there's mentions of `ws-provider` which should not be there for light client?

**Comment by 71walceli** [comment]
Yeah, right... My bad... We forgot that we had `wsProvider`s for local testnet...
